# -*- coding: utf-8 -*-
"""gramalaxmi3_EX7_qn_22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dNP9jaNehML8SGD-CCji4Inbf66TBgV
"""

#!/usr/bin/env python3
def f1(a):
  l1=[]
  for i in a:
    if(i == '{'):
      l1.append(i)
    elif(i == '}'):
      if(len(l1) == 0):
        return False
      else:
        l1.pop()  
  if(len(l1) == 0):
   return True
  else:
    return False
  
s1='{}{}{}{}{{}}'
print (f1(s1))

#!/usr/bin/env python3
def pal(s1):
  k=len(s1)//2
  a=s1[0:k]
  b= (s1[k:])
  d = {'A': 'T', 'C': 'G', 'T': 'A', 'G': 'C'}
  for i in range(0,k+1):
    
    if(a[i] != d[b[i]]):
      return False
  
  return True

j="ACACTGT"
print(pal(j))