# -*- coding: utf-8 -*-
"""gramalaxmi3_EX7_qn_14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dNP9jaNehML8SGD-CCji4Inbf66TBgV
"""

#!/usr/bin/env python3
def fib(n):
  el=[0,1]
  a=0 
  b=1
  for i in range(2,n):
      c=b+a
      a=b
      b=c
      el.append(c)
  print(el)

fib(10)