# -*- coding: utf-8 -*-
"""gramalaxmi3_EX7_qn_11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J3-emHLYhxKuwcnXfwNYquXJWqlmu8E2
"""



#!/usr/bin/env python3
s1="****"
print("enter string2 of any length")
s2=input()
s1=s1[0:2]+s2+s1[2:]
print(s1)