# -*- coding: utf-8 -*-
"""gramalaxmi3_EX7_qn_17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dNP9jaNehML8SGD-CCji4Inbf66TBgV
"""

#!/usr/bin/env python3
def med(l1,l2):
  a=sorted(l1)
  b=sorted(l2) 
  m1=((len(a)//2))
  m2=((len(b)//2))
  return [a[m1], b[m2]]

x=[1,2,4,3,8]
y=[9,5,7,35,2,5,6]
i=med(x,y)
print(i)

