# -*- coding: utf-8 -*-
"""gramalaxmi3_EX7_qn_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dNP9jaNehML8SGD-CCji4Inbf66TBgV
"""

#!/usr/bin/env python3
i=1
while i<=5 :
    print('*'*i)
    i=i+1
i=i-1
while i!=0:
    i=i-1
    print('*'*i)